services:
  db:
    image: postgres:16-alpine
    container_name: neighbourhelp-db
    restart: always
    environment:
      - POSTGRES_USER=neighbourhelp_user
      - POSTGRES_PASSWORD=neighbourhelp_dev_password
      - POSTGRES_DB=neighbourhelp_postgres # Database name
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  api:
    build: .
    container_name: neighbourhelp-api
    ports:
      - "5073:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Use 'db' as the host to connect to the container above
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=neighbourhelp_postgres;Username=neighbourhelp_user;Password=neighbourhelp_dev_password;
      - Jwt__Key=Your_Super_Secret_Fallback_Key_32_Chars_Long!
      - Jwt__Issuer=NeighborHelpApi
      - Jwt__Audience=NeighborHelpFrontend
      - Storage__Provider=S3
      - Storage__S3__BucketName=neighbourhelp-media
      - Storage__S3__Region=ap-southeast-5
      - Storage__S3__ServiceUrl=http://localstack:4566
      - Storage__S3__PublicBaseUrl=http://localhost:4566
      - Storage__S3__ForcePathStyle=true
      - Storage__S3__AccessKey=test
      - Storage__S3__SecretKey=test
      - Storage__S3__AutoCreateBucket=true
      - Storage__S3__MaxFileSizeMb=10
    depends_on:
      - db
      - localstack

  adminer:
    image: adminer
    container_name: neighbourhelp-adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  localstack:
    image: localstack/localstack:4.14.0
    container_name: neighbourhelp-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3

  redis:
    image: redis:7-alpine
    container_name: neighbourhelp-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: