services:
  db:
    image: postgres:16-alpine
    container_name: neighbourhelp-db
    restart: always
    environment:
      - POSTGRES_USER=neighbourhelp_user
      - POSTGRES_PASSWORD=neighbourhelp_dev_password
      - POSTGRES_DB=neighbourhelp_postgres # Database name
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: neighbourhelp-api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Use 'db' as the host to connect to the container above
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=neighbourhelp_postgres;Username=neighbourhelp_user;Password=neighbourhelp_dev_password;
      - Jwt__Key=Your_Super_Secret_Fallback_Key_32_Chars_Long!
      - Jwt__Issuer=NeighborHelpApi
      - Jwt__Audience=NeighborHelpFrontend
    depends_on:
      - db

volumes:
  postgres_data:
